CFLAGS+=-fstrict-aliasing -Wall -Wextra -Wshadow -Wconversion \
	  -Wpadded -Wstrict-aliasing=2 -Wstrict-overflow=4

LIB=libexecinfo
STATIC=libexecinfo.a
MAJOR=1
MINOR=1
SHEXT?=.so
SHLIB=$(LIB)$(SHEXT).$(MAJOR).$(MINOR)
SONAME=$(LIB)$(SHEXT).$(MAJOR)

SRC=$(wildcard *.c)
OBJ=$(SRC:%.c=%.o)
SOBJ=$(SRC:%.c=%.So)


%.So: %.c
	$(CC) -I. $(CPPFLAGS) $(CFLAGS) -fPIC -c $< -o $@

%.o: %.c
	$(CC) -I. $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(STATIC): $(OBJ)
	$(AR) cr $@ $^

static: $(STATIC)

$(SHLIB): $(SOBJ)
	$(CC) -fPIC $(CFLAGS) $(LDFLAGS) -shared -Wl,-soname,$(SONAME) -o $@ $^ $(LIBS)

$(SONAME): $(SHLIB)
	ln -s $< $@

$(LIB)$(SHEXT): $(SONAME)
	ln -s $< $@

shared: $(SHLIB) $(SONAME) $(LIB)$(SHEXT)
